[package]
name = "tower-lsp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tower-lsp = "0.20.0"
tokio-tungstenite = "0.20.0"
futures-util = "0.3"
serde_json = "1.0"
